name: Packge and upload to Github Package Registry

on:
  workflow_dispatch
  # push:
  #   branches:
  #     - packaging # testing for now

jobs:
  release-package:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          registry-url: "https://npm.pkg.github.com"
          scope: "@tsts-org"

      - name: Install dependencies
        run: npm install

      - name: Package library
        run: npm run package

      - name: Set package version number
        run: ./scripts/set_upstream_version.sh

      - name: Publish libraray
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
