name: Packge and upload to Github Package Registry

on:
  workflow_dispatch
  # push:
  #   branches:
  #     - packaging # testing for now

jobs:
  release-package:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          registry-url: "https://npm.pkg.github.com"
          scope: "@tsts-org"

      - run: npm version patch
      
      - name: Install dependencies
        run: npm install

      # - name: Package and Publish
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push new version
        run: git push
